import json
from langchain_core.messages import HumanMessage, SystemMessage
from langsmith import traceable

import utils
import config
from langchain_groq import ChatGroq
from engine import ChessEngine
import review_logic
import openings

SYSTEM_PROMPT = """
You are an expert chess coach creating a post-game review.

You will receive structured game facts generated by a chess engine. Treat those facts as the complete source of truth.

Your task is to write a concise, natural-sounding review that feels similar to a Chess.com Game Review summary.

Requirements:

* Write exactly 3-4 sentences.
* Maximum 80 words.
* Use clear, simple language.
* Focus on the overall story of the game.
* Mention what the stronger side did well.
* Mention the most important turning point or mistake.
* Briefly explain how that moment affected the game.
* End with one practical improvement tip for the player who made the key mistake.
* Keep the tone encouraging, constructive, and educational.

Strict Rules:

* Use only the supplied facts.
* Do not invent moves, tactics, plans, or events.
* Do not mention engine evaluations.
* Do not mention centipawns.
* Do not mention Stockfish.
* Do not mention win probability.
* Do not mention accuracy percentages.
* Do not mention ratings.
* Do not mention information that is not present in the input.
* Do not use bullet points.
* Do not use markdown.
* Output only the review text.

Desired structure:

Sentence 1:
Brief summary of how the game developed.

Sentence 2:
Describe the key turning point.

Sentence 3:
Explain how the winning side capitalized.

Sentence 4:
Move where you made a mistake/ made a good move

Sentence 5:
Give one practical coaching takeaway.
"""

@traceable
def generate_review_summary(payload: dict) -> str:
    llm = ChatGroq(
        model_name=config.MODEL_NAME, 
        temperature=0, 
        api_key=config.GROQ_API_KEY_FOR_GAME_REVIEW
    ).with_config({"run_name": "game_review_summary"})
    
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=json.dumps(payload))
    ]
    
    response = llm.invoke(messages)
    return response.content.strip()

def process_game_review(pgn_string: str) -> dict:
    """
    Orchestrates the game review process:
    1. Runs Stockfish engine analysis.
    2. Classifies moves and calculates accuracy.
    3. Extracts critical positions.
    4. Calls LLM for summary.
    5. Returns the structured JSON.
    """
    # 1. Engine Analysis
    engine = ChessEngine(depth=12, hash_size=16, threads=1)
    try:
        moves_data, headers, outcome = engine.analyze_game(pgn_string)
    finally:
        engine.close()
        
    if not moves_data:
        raise ValueError("No moves found in PGN")

    # 2. Classification & Accuracy
    moves_data, stats = review_logic.classify_moves(moves_data)
    
    # 3. Identify Opening
    # Get all FENs to pass to opening identifier
    fens = [d["fen"] for d in moves_data]
    opening_match = openings.identify_opening(fens)
    opening_name = opening_match.get("name", "Unknown Opening") if opening_match else "Unknown Opening"
    opening_eco = opening_match.get("eco", "") if opening_match else ""

    # 4. Extract Critical Positions (Worst mistake and Best move)
    critical_position = None
    best_played_move = None
    biggest_wp_loss = 0
    
    for i, data in enumerate(moves_data):
        # Find biggest mistake
        if data["classification"] in ["blunder", "mistake", "miss"] and data["wp_loss"] > biggest_wp_loss:
            biggest_wp_loss = data["wp_loss"]
            
            reason = "Wrong Move"
            if data["classification"] == "blunder":
                reason = "Critical Blunder"
            elif data["classification"] == "miss":
                reason = "Missed Win"

            critical_position = {
                "move_number": (i // 2) + 1,
                "player": data["player"].capitalize(),
                "classification": data["classification"].capitalize(),
                "reason": reason,
                "played_move": data.get("san", ""),
                "engine_recommended_move": data.get("best_move", ""),
                "fen": data["fen"]
            }
            
        # Find best move (first Brilliant or Great move found)
        if data["classification"] in ["brilliant", "great"] and not best_played_move:
            best_played_move = {
                "move_number": (i // 2) + 1,
                "player": data["player"].capitalize(),
                "classification": data["classification"].capitalize(),
                "played_move": data.get("san", "")
            }

    # Extract Eval Graph
    eval_graph = []
    for i, data in enumerate(moves_data):
        eval_graph.append({
            "move": i + 1, # ply number
            "eval": data["eval_graph"]
        })

    # Prepare LLM Payload
    winner = headers.get("Result", "*")
    if winner == "*":
        # Infer from outcome if not explicitly in headers
        if outcome is not None:
            if outcome.winner == True:
                winner_text = "White"
                winner = "1-0"
            elif outcome.winner == False:
                winner_text = "Black"
                winner = "0-1"
            else:
                winner_text = "Draw"
                winner = "1/2-1/2"
        else:
            winner_text = "Draw" # Default if game stopped
    else:
        if winner == "1-0":
            winner_text = "White"
        elif winner == "0-1":
            winner_text = "Black"
        else:
            winner_text = "Draw"

    llm_payload = {
        "payload": {
            "opening": opening_name,
            "result": winner_text,
            "players": {
                "white": stats["white"],
                "black": stats["black"]
            },
            "critical_mistake": critical_position,
            "notable_good_move": best_played_move
        }
    }

    # 6. Build Final JSON
    result = {
        "opening": {
            "name": opening_name,
            "eco": opening_eco
        },
        "result": winner,
        "players": {
            "white": stats["white"],
            "black": stats["black"]
        },
        "moves": [
            {
                "san": m["san"],
                "player": m["player"],
                "classification": m["classification"],
                "eval": m["eval_graph"]
            }
            for m in moves_data
        ],
        "eval_graph": eval_graph,
        "critical_positions": [critical_position] if critical_position else [],
        "llm_payload": llm_payload
    }
    
    return result
